METADATA_UNIQUE = b"cq:extension:unique"
METADATA_PRIMARY_KEY = b"cq:extension:primary_key"
METADATA_CONSTRAINT_NAME = b"cq:extension:constraint_name"
METADATA_INCREMENTAL = b"cq:extension:incremental"

METADATA_TRUE = b"true"
METADATA_FALSE = b"false"
METADATA_TABLE_NAME = b"cq:table_name"
METADATA_TABLE_DESCRIPTION = b"cq:table_description"
METADATA_TABLE_TITLE = b"cq:table_title"
METADATA_TABLE_DEPENDS_ON = b"cq:table_depends_on"
